/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Database.MyDatabase;
import Interface.UserInterface;
import Project.Main;
import Project.Pesanan;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author ACER
 */
public class Customer extends javax.swing.JFrame implements UserInterface{

    /**
     * Creates new form Customerpage
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableSearch = new javax.swing.JTable();
        OrderPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableOrder = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbGame = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbJumlah = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        btnTopUp = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parentPanel.setBackground(new java.awt.Color(158, 71, 132));
        parentPanel.setOpaque(false);

        menuPanel.setBackground(new java.awt.Color(158, 71, 132));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        menuPanel.setOpaque(false);

        btnLogout.setBackground(new java.awt.Color(102, 0, 0));
        btnLogout.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("BACK");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(102, 52, 127));
        btnHome.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("HOME");
        btnHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnOrder.setBackground(new java.awt.Color(102, 52, 127));
        btnOrder.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnOrder.setText("ORDER");
        btnOrder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 176, 45));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("POCHINOK");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel14.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(235, 176, 45));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("STORE");
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        mainPanel.setBackground(new java.awt.Color(158, 71, 132));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        mainPanel.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        mainPanel.setOpaque(false);
        mainPanel.setPreferredSize(new java.awt.Dimension(939, 480));
        mainPanel.setLayout(new java.awt.CardLayout());

        HomePanel.setBackground(new java.awt.Color(158, 71, 132));
        HomePanel.setOpaque(false);

        txtSearch.setBackground(new java.awt.Color(255, 205, 56));
        txtSearch.setFont(new java.awt.Font("Futura Md BT", 1, 16)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        txtSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Home Page Pochinok Store");

        TableSearch.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        TableSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Game", "Jumlah", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TableSearch.setRowHeight(22);
        jScrollPane5.setViewportView(TableSearch);

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSearch)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)))
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        mainPanel.add(HomePanel, "card4");

        OrderPanel.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Order Top Up Pochinok Store");

        TableOrder.setBackground(new java.awt.Color(249, 217, 73));
        TableOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TableOrder.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        TableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Game", "Mata Uang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableOrder.setGridColor(new java.awt.Color(0, 0, 0));
        TableOrder.setRowHeight(22);
        TableOrder.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(TableOrder);

        jLabel8.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(253, 226, 243));
        jLabel8.setText("Daftar Harga Top Up");

        jLabel9.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Game");

        jLabel10.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(253, 226, 243));
        jLabel10.setText("Total Harga");

        txtID.setBackground(new java.awt.Color(249, 217, 73));
        txtID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(253, 226, 243));
        jLabel11.setText("ID Akun");

        cbGame.setBackground(new java.awt.Color(249, 217, 73));
        cbGame.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        cbGame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbGame.setSelectedIndex(-1);
        cbGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGameActionPerformed(evt);
            }
        });

        txtTotal.setBackground(new java.awt.Color(249, 217, 73));
        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTotal.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(253, 226, 243));
        jLabel12.setText("Nickname Akun");

        cbJumlah.setBackground(new java.awt.Color(249, 217, 73));
        cbJumlah.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        cbJumlah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbJumlah.setSelectedIndex(-1);
        cbJumlah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJumlahActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(253, 226, 243));
        jLabel13.setText("Jumlah Top Up");

        txtNickname.setBackground(new java.awt.Color(249, 217, 73));
        txtNickname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnTopUp.setBackground(new java.awt.Color(0, 159, 189));
        btnTopUp.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnTopUp.setForeground(new java.awt.Color(249, 226, 175));
        btnTopUp.setText("Top Up");
        btnTopUp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTopUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUpActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 159, 189));
        btnClear.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(249, 226, 175));
        btnClear.setText("Clear");
        btnClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrderPanelLayout = new javax.swing.GroupLayout(OrderPanel);
        OrderPanel.setLayout(OrderPanelLayout);
        OrderPanelLayout.setHorizontalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbJumlah, javax.swing.GroupLayout.Alignment.LEADING, 0, 240, Short.MAX_VALUE)
                        .addComponent(txtNickname, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbGame, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderPanelLayout.createSequentialGroup()
                        .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OrderPanelLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btnTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(122, 122, 122))))
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel7)
                .addGap(0, 162, Short.MAX_VALUE))
        );
        OrderPanelLayout.setVerticalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(OrderPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(OrderPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(17, 17, 17)))
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderPanelLayout.createSequentialGroup()
                        .addComponent(cbGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OrderPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        mainPanel.add(OrderPanel, "card3");

        javax.swing.GroupLayout parentPanelLayout = new javax.swing.GroupLayout(parentPanel);
        parentPanel.setLayout(parentPanelLayout);
        parentPanelLayout.setHorizontalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        parentPanelLayout.setVerticalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 55, 860, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/bg baru.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
//    override dan overloading
    @Override
    public void display(){
        cbGame.removeAllItems();
        cbGame.addItem(" ");
        for (int i = 0 ; i < Main.dataGame.size() ; i++){
            cbGame.addItem(Main.dataGame.get(i).getGame());
        }
    }
    
    private void display_jumlah(String game){
        int idx = Main.cari_game(game);
        
        cbJumlah.removeAllItems();
        cbJumlah.addItem(" ");
        if (idx != -1){
            for (int i = 0 ; i < Main.dataGame.get(idx).getVarian().size() ; i++){
                String jumlah = Main.dataGame.get(idx).getVarian().get(i).get(0).toString();
                String mataUang = Main.dataGame.get(idx).getMataUang();
                cbJumlah.addItem(jumlah + " " + mataUang);
            }
        }
    }
    
//    override dan overloading
    @Override
    public void display(String game){
        int idx = Main.cari_game(game);
        
//        atur kolom header
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Jumlah");
        model.addColumn("Harga");
        
//        kalo misalnya data ketemu, maka akan diambil data dari arraylistnya ke tabel
        if (idx != -1){
            for (int i = 0 ; i < Main.dataGame.get(idx).getVarian().size() ; i++){
                String jumlah = Main.dataGame.get(idx).getVarian().get(i).get(0).toString() + " " + Main.dataGame.get(idx).getMataUang();
                String harga = "Rp" + Main.dataGame.get(idx).getVarian().get(i).get(1);
                model.addRow(new Object[] {(i+1), jumlah, harga});
            }
        }
        
//        set model dan atur lebar kolom
        TableOrder.setModel(model);
        TableOrder.getColumnModel().getColumn(0).setPreferredWidth(1);
        TableOrder.getColumnModel().getColumn(1).setPreferredWidth(100);
        TableOrder.getColumnModel().getColumn(2).setPreferredWidth(100);
        
//        align nomor to center
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        TableColumnModel columnModel = TableOrder.getColumnModel();
        for (int i = 0 ; i < 3 ;i++){
            columnModel.getColumn(i).setCellRenderer(centerRenderer);
        }
        TableOrder.setDefaultEditor(Object.class, null);
    }
    
    private boolean cek(){
        if (cbGame.getSelectedIndex() < 1){
            JOptionPane.showMessageDialog(this, "Pilih Game Yang Mau Di Top Up Dulu Masbro!", "Sekedar Mengingatkan", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (txtID.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "ID Akunnya Tidak Boleh Kosong Masbro!", "Sekedar Mengingatkan", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (txtNickname.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Nickname Akunnya Tidak Boleh Kosong Masbro!", "Sekedar Mengingatkan", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (cbJumlah.getSelectedIndex() < 1){
            JOptionPane.showMessageDialog(this, "Pilih Jumlah Top Upnya Dulu Masbro!", "Sekedar Mengingatkan", JOptionPane.WARNING_MESSAGE);
            return false;
        }
            
        return true;
    }
    
    private void cls(){
        cbGame.setSelectedIndex(0);
        cbJumlah.setSelectedIndex(0);
        txtID.setText("");
        txtNickname.setText("");
    }
    
    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        HomePanel.setVisible(false);
        OrderPanel.setVisible(true);
        MyDatabase.read_game();
        MyDatabase.read_varian();
        cls();
        display();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        HomePanel.setVisible(true);
        OrderPanel.setVisible(false);
        txtSearch.setText("");
        MyDatabase.search("", 2);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Landingpage land = new Landingpage();
        land.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        MyDatabase.search(txtSearch.getText(), 2);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        cls();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopUpActionPerformed
        if (cek() == true){
            int pilih = JOptionPane.showConfirmDialog(null, "Yakin Data Akun Anda Sudah Benar?", "Meyakinkan", JOptionPane.YES_NO_OPTION);
            if (pilih == JOptionPane.YES_OPTION){
                String game = cbGame.getSelectedItem().toString();
                String id_akun = txtID.getText();
                String nickname = txtNickname.getText();
                int idx_game = Main.cari_game(game);
                String mataUang = Main.dataGame.get(idx_game).getMataUang();
                int idx_topup = cbJumlah.getSelectedIndex() - 1;
                int jumlah = Main.dataGame.get(idx_game).getVarian().get(idx_topup).get(0);
                int harga = Main.dataGame.get(idx_game).getVarian().get(idx_topup).get(1);
                LocalDateTime timeNow = LocalDateTime.now();
                DateTimeFormatter waktu = DateTimeFormatter.ofPattern("E, MMM dd yyyy HH:mm:ss");
                String waktuSekarang = timeNow.format(waktu);
                Pesanan newData = new Pesanan(jumlah, harga, game, id_akun, nickname, waktuSekarang, mataUang);

                Main.dataPesanan.add(newData);
                MyDatabase.insert_transaksi(game, jumlah, harga, id_akun, nickname, waktuSekarang);
                Main.dataPesanan.get(Main.dataPesanan.size()-1).action();
            }
        }
    }//GEN-LAST:event_btnTopUpActionPerformed

    private void cbGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGameActionPerformed
        if (cbGame.getItemCount() > 0){
            String game = cbGame.getSelectedItem().toString();
            display_jumlah(game);
            display(game);
            if (cbGame.getSelectedIndex() > 0){
                cbJumlah.setEnabled(true);
            } else {
                cbJumlah.setEnabled(false);
            }
        } 
    }//GEN-LAST:event_cbGameActionPerformed

    private void cbJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJumlahActionPerformed
//        if (cbJumlah.getItemCount() > 0){
            if (cbJumlah.getSelectedIndex() > 0){
                String game = cbGame.getSelectedItem().toString();
                int idx_game = Main.cari_game(game);
                int idx_jumlah = cbJumlah.getSelectedIndex() - 1;
                String harga = "Rp" + Main.dataGame.get(idx_game).getVarian().get(idx_jumlah).get(1).toString();
                txtTotal.setText(harga);
            } else {
                txtTotal.setText("");
            }
//        }
    }//GEN-LAST:event_cbJumlahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JTable TableOrder;
    public static javax.swing.JTable TableSearch;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnTopUp;
    private javax.swing.JComboBox<String> cbGame;
    private javax.swing.JComboBox<String> cbJumlah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNickname;
    public static javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
